using ERP_Pro.Domain.Common.Entities;
using ERP_Pro.Domain.Journals.Enums;
using System;
using System.Collections.Generic;

namespace ERP_Pro.Domain.Journals.Entities
{
    public class JournalEntry : AggregateRoot<int>
    {
        public string JournalNumber { get; set; }
        public DateTime Date { get; set; }
        public string Reference { get; set; }
        public int? BranchId { get; set; }
        public string Description { get; set; }
        public string SourceModule { get; set; }
        public string SourceDocumentNo { get; set; }
        public JournalType JournalType { get; set; }
        public JournalStatus Status { get; set; }
        public string Period { get; set; }
        public ICollection<JournalDetail> Details { get; set; }
        public string Attachments { get; set; }
        public bool IsAutoGenerated { get; set; }
    }
}